//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Desenv\KameProgressScript\KameProgressParser\ABLProgress.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IABLProgressListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class ABLProgressBaseListener : IABLProgressListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScript([NotNull] ABLProgressParser.ScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScript([NotNull] ABLProgressParser.ScriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] ABLProgressParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] ABLProgressParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] ABLProgressParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] ABLProgressParser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceCycleOnLimitValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequenceCycleOnLimitValue([NotNull] ABLProgressParser.SequenceCycleOnLimitValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceCycleOnLimitValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequenceCycleOnLimitValue([NotNull] ABLProgressParser.SequenceCycleOnLimitValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceIncrementValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequenceIncrementValue([NotNull] ABLProgressParser.SequenceIncrementValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceIncrementValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequenceIncrementValue([NotNull] ABLProgressParser.SequenceIncrementValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceInitialValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequenceInitialValue([NotNull] ABLProgressParser.SequenceInitialValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceInitialValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequenceInitialValue([NotNull] ABLProgressParser.SequenceInitialValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceMinValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequenceMinValue([NotNull] ABLProgressParser.SequenceMinValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceMinValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequenceMinValue([NotNull] ABLProgressParser.SequenceMinValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceForeignName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequenceForeignName([NotNull] ABLProgressParser.SequenceForeignNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceForeignName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequenceForeignName([NotNull] ABLProgressParser.SequenceForeignNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceForeigOwner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequenceForeigOwner([NotNull] ABLProgressParser.SequenceForeigOwnerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceForeigOwner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequenceForeigOwner([NotNull] ABLProgressParser.SequenceForeigOwnerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequenceObject([NotNull] ABLProgressParser.SequenceObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequenceObject([NotNull] ABLProgressParser.SequenceObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequenceOptions([NotNull] ABLProgressParser.SequenceOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequenceOptions([NotNull] ABLProgressParser.SequenceOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexObject([NotNull] ABLProgressParser.IndexObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexObject([NotNull] ABLProgressParser.IndexObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexOnValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexOnValue([NotNull] ABLProgressParser.IndexOnValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexOnValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexOnValue([NotNull] ABLProgressParser.IndexOnValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexForeignNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexForeignNameValue([NotNull] ABLProgressParser.IndexForeignNameValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexForeignNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexForeignNameValue([NotNull] ABLProgressParser.IndexForeignNameValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexNumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexNumValue([NotNull] ABLProgressParser.IndexNumValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexNumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexNumValue([NotNull] ABLProgressParser.IndexNumValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexFieldValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexFieldValue([NotNull] ABLProgressParser.IndexFieldValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexFieldValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexFieldValue([NotNull] ABLProgressParser.IndexFieldValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexFields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexFields([NotNull] ABLProgressParser.IndexFieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexFields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexFields([NotNull] ABLProgressParser.IndexFieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexOptions([NotNull] ABLProgressParser.IndexOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexOptions([NotNull] ABLProgressParser.IndexOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexAreavalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexAreavalue([NotNull] ABLProgressParser.IndexAreavalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexAreavalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexAreavalue([NotNull] ABLProgressParser.IndexAreavalueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableObject([NotNull] ABLProgressParser.TableObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableObject([NotNull] ABLProgressParser.TableObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableOptions([NotNull] ABLProgressParser.TableOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableOptions([NotNull] ABLProgressParser.TableOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableAreaValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableAreaValue([NotNull] ABLProgressParser.TableAreaValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableAreaValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableAreaValue([NotNull] ABLProgressParser.TableAreaValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableDumpNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableDumpNameValue([NotNull] ABLProgressParser.TableDumpNameValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableDumpNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableDumpNameValue([NotNull] ABLProgressParser.TableDumpNameValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableForeignNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableForeignNameValue([NotNull] ABLProgressParser.TableForeignNameValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableForeignNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableForeignNameValue([NotNull] ABLProgressParser.TableForeignNameValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableForeignOwnerValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableForeignOwnerValue([NotNull] ABLProgressParser.TableForeignOwnerValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableForeignOwnerValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableForeignOwnerValue([NotNull] ABLProgressParser.TableForeignOwnerValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableProgressRecidValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableProgressRecidValue([NotNull] ABLProgressParser.TableProgressRecidValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableProgressRecidValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableProgressRecidValue([NotNull] ABLProgressParser.TableProgressRecidValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableType([NotNull] ABLProgressParser.TableTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableType([NotNull] ABLProgressParser.TableTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldObject([NotNull] ABLProgressParser.FieldObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldObject([NotNull] ABLProgressParser.FieldObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldDataTypeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDataTypeValue([NotNull] ABLProgressParser.FieldDataTypeValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldDataTypeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDataTypeValue([NotNull] ABLProgressParser.FieldDataTypeValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldForeignCodeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldForeignCodeValue([NotNull] ABLProgressParser.FieldForeignCodeValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldForeignCodeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldForeignCodeValue([NotNull] ABLProgressParser.FieldForeignCodeValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldForeignNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldForeignNameValue([NotNull] ABLProgressParser.FieldForeignNameValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldForeignNameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldForeignNameValue([NotNull] ABLProgressParser.FieldForeignNameValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldForeignPosValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldForeignPosValue([NotNull] ABLProgressParser.FieldForeignPosValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldForeignPosValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldForeignPosValue([NotNull] ABLProgressParser.FieldForeignPosValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldFormatValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldFormatValue([NotNull] ABLProgressParser.FieldFormatValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldFormatValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldFormatValue([NotNull] ABLProgressParser.FieldFormatValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldInitialValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldInitialValue([NotNull] ABLProgressParser.FieldInitialValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldInitialValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldInitialValue([NotNull] ABLProgressParser.FieldInitialValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldMisc13Value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldMisc13Value([NotNull] ABLProgressParser.FieldMisc13ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldMisc13Value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldMisc13Value([NotNull] ABLProgressParser.FieldMisc13ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldMisc14Value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldMisc14Value([NotNull] ABLProgressParser.FieldMisc14ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldMisc14Value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldMisc14Value([NotNull] ABLProgressParser.FieldMisc14ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldMisc15Value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldMisc15Value([NotNull] ABLProgressParser.FieldMisc15ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldMisc15Value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldMisc15Value([NotNull] ABLProgressParser.FieldMisc15ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldOfValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldOfValue([NotNull] ABLProgressParser.FieldOfValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldOfValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldOfValue([NotNull] ABLProgressParser.FieldOfValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldClobCodePageValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldClobCodePageValue([NotNull] ABLProgressParser.FieldClobCodePageValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldClobCodePageValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldClobCodePageValue([NotNull] ABLProgressParser.FieldClobCodePageValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldClobCollationValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldClobCollationValue([NotNull] ABLProgressParser.FieldClobCollationValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldClobCollationValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldClobCollationValue([NotNull] ABLProgressParser.FieldClobCollationValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldClobTypeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldClobTypeValue([NotNull] ABLProgressParser.FieldClobTypeValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldClobTypeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldClobTypeValue([NotNull] ABLProgressParser.FieldClobTypeValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldOptions([NotNull] ABLProgressParser.FieldOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldOptions([NotNull] ABLProgressParser.FieldOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldOrderValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldOrderValue([NotNull] ABLProgressParser.FieldOrderValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldOrderValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldOrderValue([NotNull] ABLProgressParser.FieldOrderValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldPositionValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldPositionValue([NotNull] ABLProgressParser.FieldPositionValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldPositionValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldPositionValue([NotNull] ABLProgressParser.FieldPositionValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldShadowColValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldShadowColValue([NotNull] ABLProgressParser.FieldShadowColValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldShadowColValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldShadowColValue([NotNull] ABLProgressParser.FieldShadowColValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.objectName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectName([NotNull] ABLProgressParser.ObjectNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.objectName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectName([NotNull] ABLProgressParser.ObjectNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.foreignTypeValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeignTypeValues([NotNull] ABLProgressParser.ForeignTypeValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.foreignTypeValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeignTypeValues([NotNull] ABLProgressParser.ForeignTypeValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.quotedString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuotedString([NotNull] ABLProgressParser.QuotedStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.quotedString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuotedString([NotNull] ABLProgressParser.QuotedStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.unquotedString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnquotedString([NotNull] ABLProgressParser.UnquotedStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.unquotedString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnquotedString([NotNull] ABLProgressParser.UnquotedStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldFormatMask"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldFormatMask([NotNull] ABLProgressParser.FieldFormatMaskContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldFormatMask"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldFormatMask([NotNull] ABLProgressParser.FieldFormatMaskContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.dataTypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataTypes([NotNull] ABLProgressParser.DataTypesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.dataTypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataTypes([NotNull] ABLProgressParser.DataTypesContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
