//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Desenv\KameProgressScript\KameProgressParser\ABLProgress.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ABLProgressParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IABLProgressVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] ABLProgressParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] ABLProgressParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction([NotNull] ABLProgressParser.ActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.sequenceCycleOnLimitValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequenceCycleOnLimitValue([NotNull] ABLProgressParser.SequenceCycleOnLimitValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.sequenceIncrementValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequenceIncrementValue([NotNull] ABLProgressParser.SequenceIncrementValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.sequenceInitialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequenceInitialValue([NotNull] ABLProgressParser.SequenceInitialValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.sequenceMinValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequenceMinValue([NotNull] ABLProgressParser.SequenceMinValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.sequenceForeignName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequenceForeignName([NotNull] ABLProgressParser.SequenceForeignNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.sequenceForeigOwner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequenceForeigOwner([NotNull] ABLProgressParser.SequenceForeigOwnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.sequenceObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequenceObject([NotNull] ABLProgressParser.SequenceObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.sequenceOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequenceOptions([NotNull] ABLProgressParser.SequenceOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.indexObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexObject([NotNull] ABLProgressParser.IndexObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.indexOnValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexOnValue([NotNull] ABLProgressParser.IndexOnValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.indexForeignNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexForeignNameValue([NotNull] ABLProgressParser.IndexForeignNameValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.indexNumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexNumValue([NotNull] ABLProgressParser.IndexNumValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.indexFieldValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexFieldValue([NotNull] ABLProgressParser.IndexFieldValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.indexFields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexFields([NotNull] ABLProgressParser.IndexFieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.indexOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexOptions([NotNull] ABLProgressParser.IndexOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.indexAreavalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexAreavalue([NotNull] ABLProgressParser.IndexAreavalueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.tableObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableObject([NotNull] ABLProgressParser.TableObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.tableOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableOptions([NotNull] ABLProgressParser.TableOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.tableAreaValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableAreaValue([NotNull] ABLProgressParser.TableAreaValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.tableDumpNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableDumpNameValue([NotNull] ABLProgressParser.TableDumpNameValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.tableForeignNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableForeignNameValue([NotNull] ABLProgressParser.TableForeignNameValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.tableForeignOwnerValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableForeignOwnerValue([NotNull] ABLProgressParser.TableForeignOwnerValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.tableProgressRecidValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableProgressRecidValue([NotNull] ABLProgressParser.TableProgressRecidValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableType([NotNull] ABLProgressParser.TableTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldObject([NotNull] ABLProgressParser.FieldObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldDataTypeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDataTypeValue([NotNull] ABLProgressParser.FieldDataTypeValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldForeignCodeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldForeignCodeValue([NotNull] ABLProgressParser.FieldForeignCodeValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldForeignNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldForeignNameValue([NotNull] ABLProgressParser.FieldForeignNameValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldForeignPosValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldForeignPosValue([NotNull] ABLProgressParser.FieldForeignPosValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldFormatValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldFormatValue([NotNull] ABLProgressParser.FieldFormatValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldInitialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldInitialValue([NotNull] ABLProgressParser.FieldInitialValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldMisc13Value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldMisc13Value([NotNull] ABLProgressParser.FieldMisc13ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldMisc14Value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldMisc14Value([NotNull] ABLProgressParser.FieldMisc14ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldMisc15Value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldMisc15Value([NotNull] ABLProgressParser.FieldMisc15ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldOfValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldOfValue([NotNull] ABLProgressParser.FieldOfValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldClobCodePageValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldClobCodePageValue([NotNull] ABLProgressParser.FieldClobCodePageValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldClobCollationValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldClobCollationValue([NotNull] ABLProgressParser.FieldClobCollationValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldClobTypeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldClobTypeValue([NotNull] ABLProgressParser.FieldClobTypeValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldOptions([NotNull] ABLProgressParser.FieldOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldOrderValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldOrderValue([NotNull] ABLProgressParser.FieldOrderValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldPositionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldPositionValue([NotNull] ABLProgressParser.FieldPositionValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldShadowColValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldShadowColValue([NotNull] ABLProgressParser.FieldShadowColValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.objectName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectName([NotNull] ABLProgressParser.ObjectNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.foreignTypeValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeignTypeValues([NotNull] ABLProgressParser.ForeignTypeValuesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.quotedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuotedString([NotNull] ABLProgressParser.QuotedStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.unquotedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnquotedString([NotNull] ABLProgressParser.UnquotedStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.fieldFormatMask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldFormatMask([NotNull] ABLProgressParser.FieldFormatMaskContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ABLProgressParser.dataTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataTypes([NotNull] ABLProgressParser.DataTypesContext context);
}
