//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Desenv\KameProgressScript\KameProgressParser\ABLProgress.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ABLProgressParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IABLProgressListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScript([NotNull] ABLProgressParser.ScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScript([NotNull] ABLProgressParser.ScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] ABLProgressParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] ABLProgressParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAction([NotNull] ABLProgressParser.ActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAction([NotNull] ABLProgressParser.ActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceCycleOnLimitValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSequenceCycleOnLimitValue([NotNull] ABLProgressParser.SequenceCycleOnLimitValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceCycleOnLimitValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSequenceCycleOnLimitValue([NotNull] ABLProgressParser.SequenceCycleOnLimitValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceIncrementValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSequenceIncrementValue([NotNull] ABLProgressParser.SequenceIncrementValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceIncrementValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSequenceIncrementValue([NotNull] ABLProgressParser.SequenceIncrementValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceInitialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSequenceInitialValue([NotNull] ABLProgressParser.SequenceInitialValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceInitialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSequenceInitialValue([NotNull] ABLProgressParser.SequenceInitialValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceMinValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSequenceMinValue([NotNull] ABLProgressParser.SequenceMinValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceMinValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSequenceMinValue([NotNull] ABLProgressParser.SequenceMinValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceForeignName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSequenceForeignName([NotNull] ABLProgressParser.SequenceForeignNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceForeignName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSequenceForeignName([NotNull] ABLProgressParser.SequenceForeignNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceForeigOwner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSequenceForeigOwner([NotNull] ABLProgressParser.SequenceForeigOwnerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceForeigOwner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSequenceForeigOwner([NotNull] ABLProgressParser.SequenceForeigOwnerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSequenceObject([NotNull] ABLProgressParser.SequenceObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSequenceObject([NotNull] ABLProgressParser.SequenceObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.sequenceOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSequenceOptions([NotNull] ABLProgressParser.SequenceOptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.sequenceOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSequenceOptions([NotNull] ABLProgressParser.SequenceOptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexObject([NotNull] ABLProgressParser.IndexObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexObject([NotNull] ABLProgressParser.IndexObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexOnValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexOnValue([NotNull] ABLProgressParser.IndexOnValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexOnValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexOnValue([NotNull] ABLProgressParser.IndexOnValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexForeignNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexForeignNameValue([NotNull] ABLProgressParser.IndexForeignNameValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexForeignNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexForeignNameValue([NotNull] ABLProgressParser.IndexForeignNameValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexNumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexNumValue([NotNull] ABLProgressParser.IndexNumValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexNumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexNumValue([NotNull] ABLProgressParser.IndexNumValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexFieldValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexFieldValue([NotNull] ABLProgressParser.IndexFieldValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexFieldValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexFieldValue([NotNull] ABLProgressParser.IndexFieldValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexFields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexFields([NotNull] ABLProgressParser.IndexFieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexFields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexFields([NotNull] ABLProgressParser.IndexFieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexOptions([NotNull] ABLProgressParser.IndexOptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexOptions([NotNull] ABLProgressParser.IndexOptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.indexAreavalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexAreavalue([NotNull] ABLProgressParser.IndexAreavalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.indexAreavalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexAreavalue([NotNull] ABLProgressParser.IndexAreavalueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableObject([NotNull] ABLProgressParser.TableObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableObject([NotNull] ABLProgressParser.TableObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableOptions([NotNull] ABLProgressParser.TableOptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableOptions([NotNull] ABLProgressParser.TableOptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableAreaValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableAreaValue([NotNull] ABLProgressParser.TableAreaValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableAreaValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableAreaValue([NotNull] ABLProgressParser.TableAreaValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableDumpNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableDumpNameValue([NotNull] ABLProgressParser.TableDumpNameValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableDumpNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableDumpNameValue([NotNull] ABLProgressParser.TableDumpNameValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableForeignNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableForeignNameValue([NotNull] ABLProgressParser.TableForeignNameValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableForeignNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableForeignNameValue([NotNull] ABLProgressParser.TableForeignNameValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableForeignOwnerValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableForeignOwnerValue([NotNull] ABLProgressParser.TableForeignOwnerValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableForeignOwnerValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableForeignOwnerValue([NotNull] ABLProgressParser.TableForeignOwnerValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableProgressRecidValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableProgressRecidValue([NotNull] ABLProgressParser.TableProgressRecidValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableProgressRecidValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableProgressRecidValue([NotNull] ABLProgressParser.TableProgressRecidValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableType([NotNull] ABLProgressParser.TableTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableType([NotNull] ABLProgressParser.TableTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldObject([NotNull] ABLProgressParser.FieldObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldObject([NotNull] ABLProgressParser.FieldObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldDataTypeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDataTypeValue([NotNull] ABLProgressParser.FieldDataTypeValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldDataTypeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDataTypeValue([NotNull] ABLProgressParser.FieldDataTypeValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldForeignCodeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldForeignCodeValue([NotNull] ABLProgressParser.FieldForeignCodeValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldForeignCodeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldForeignCodeValue([NotNull] ABLProgressParser.FieldForeignCodeValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldForeignNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldForeignNameValue([NotNull] ABLProgressParser.FieldForeignNameValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldForeignNameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldForeignNameValue([NotNull] ABLProgressParser.FieldForeignNameValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldForeignPosValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldForeignPosValue([NotNull] ABLProgressParser.FieldForeignPosValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldForeignPosValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldForeignPosValue([NotNull] ABLProgressParser.FieldForeignPosValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldFormatValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldFormatValue([NotNull] ABLProgressParser.FieldFormatValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldFormatValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldFormatValue([NotNull] ABLProgressParser.FieldFormatValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldInitialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldInitialValue([NotNull] ABLProgressParser.FieldInitialValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldInitialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldInitialValue([NotNull] ABLProgressParser.FieldInitialValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldMisc13Value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldMisc13Value([NotNull] ABLProgressParser.FieldMisc13ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldMisc13Value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldMisc13Value([NotNull] ABLProgressParser.FieldMisc13ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldMisc14Value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldMisc14Value([NotNull] ABLProgressParser.FieldMisc14ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldMisc14Value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldMisc14Value([NotNull] ABLProgressParser.FieldMisc14ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldMisc15Value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldMisc15Value([NotNull] ABLProgressParser.FieldMisc15ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldMisc15Value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldMisc15Value([NotNull] ABLProgressParser.FieldMisc15ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldOfValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldOfValue([NotNull] ABLProgressParser.FieldOfValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldOfValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldOfValue([NotNull] ABLProgressParser.FieldOfValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldClobCodePageValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldClobCodePageValue([NotNull] ABLProgressParser.FieldClobCodePageValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldClobCodePageValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldClobCodePageValue([NotNull] ABLProgressParser.FieldClobCodePageValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldClobCollationValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldClobCollationValue([NotNull] ABLProgressParser.FieldClobCollationValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldClobCollationValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldClobCollationValue([NotNull] ABLProgressParser.FieldClobCollationValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldClobTypeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldClobTypeValue([NotNull] ABLProgressParser.FieldClobTypeValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldClobTypeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldClobTypeValue([NotNull] ABLProgressParser.FieldClobTypeValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldOptions([NotNull] ABLProgressParser.FieldOptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldOptions([NotNull] ABLProgressParser.FieldOptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldOrderValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldOrderValue([NotNull] ABLProgressParser.FieldOrderValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldOrderValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldOrderValue([NotNull] ABLProgressParser.FieldOrderValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldPositionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldPositionValue([NotNull] ABLProgressParser.FieldPositionValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldPositionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldPositionValue([NotNull] ABLProgressParser.FieldPositionValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldShadowColValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldShadowColValue([NotNull] ABLProgressParser.FieldShadowColValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldShadowColValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldShadowColValue([NotNull] ABLProgressParser.FieldShadowColValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.objectName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectName([NotNull] ABLProgressParser.ObjectNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.objectName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectName([NotNull] ABLProgressParser.ObjectNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.foreignTypeValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeignTypeValues([NotNull] ABLProgressParser.ForeignTypeValuesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.foreignTypeValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeignTypeValues([NotNull] ABLProgressParser.ForeignTypeValuesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.quotedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuotedString([NotNull] ABLProgressParser.QuotedStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.quotedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuotedString([NotNull] ABLProgressParser.QuotedStringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.unquotedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnquotedString([NotNull] ABLProgressParser.UnquotedStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.unquotedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnquotedString([NotNull] ABLProgressParser.UnquotedStringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.fieldFormatMask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldFormatMask([NotNull] ABLProgressParser.FieldFormatMaskContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.fieldFormatMask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldFormatMask([NotNull] ABLProgressParser.FieldFormatMaskContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ABLProgressParser.dataTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataTypes([NotNull] ABLProgressParser.DataTypesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ABLProgressParser.dataTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataTypes([NotNull] ABLProgressParser.DataTypesContext context);
}
